// This file was generated by counterfeiter
package authfakes

import (
	"net/http"
	"sync"

	"github.com/sgravrock/flickr-show-privates/auth"
)

type FakeAuthenticator struct {
	AuthenticateStub        func() (*http.Client, error)
	authenticateMutex       sync.RWMutex
	authenticateArgsForCall []struct{}
	authenticateReturns     struct {
		result1 *http.Client
		result2 error
	}
}

func (fake *FakeAuthenticator) Authenticate() (*http.Client, error) {
	fake.authenticateMutex.Lock()
	fake.authenticateArgsForCall = append(fake.authenticateArgsForCall, struct{}{})
	fake.authenticateMutex.Unlock()
	if fake.AuthenticateStub != nil {
		return fake.AuthenticateStub()
	} else {
		return fake.authenticateReturns.result1, fake.authenticateReturns.result2
	}
}

func (fake *FakeAuthenticator) AuthenticateCallCount() int {
	fake.authenticateMutex.RLock()
	defer fake.authenticateMutex.RUnlock()
	return len(fake.authenticateArgsForCall)
}

func (fake *FakeAuthenticator) AuthenticateReturns(result1 *http.Client, result2 error) {
	fake.AuthenticateStub = nil
	fake.authenticateReturns = struct {
		result1 *http.Client
		result2 error
	}{result1, result2}
}

var _ auth.Authenticator = new(FakeAuthenticator)
